### ISSUE TITLE
Problem with installation (Node v8.1.2)

### ISSUE THREAD

**Issue by avish9** [serverless/components#165]
Installation command:
_**npm install --global serverless-components**_

Didn't work with:
(1) Node v8.1.2
(2) NPM 5.6.0
(3) On MacOS Sierra

Solved after upgrading to Node v9.11.1, NPM 5.8.0.

Stack Trace:
```bash
components $ npm install --global serverless-components
/usr/local/bin/components -> /usr/local/lib/node_modules/serverless-components/bin/components

> serverless-components@0.1.2 postinstall /usr/local/lib/node_modules/serverless-components
> node ./scripts/postinstall.js

/usr/local/lib/node_modules/serverless-components/src/utils/index.js:16
  ...components,
  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless-components/scripts/postinstall.js:7:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless-components@0.1.2 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless-components@0.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by avish9** [comment]
Thanks @brianneisler 👍 
I don't think I had harmony disabled on node8... Anyways, I'm using node9 and it all works fine :)

**Comment by benmcp** [comment]
If anyone else is interested/reading this, `Object Rest/Spread Properties` is only supported for [Node 8.3.0+](http://node.green/#ES2018-features-object-rest-spread-properties). Unless, as you mentioned Brian, you enable harmony 👍

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue no longer exists.
