### ISSUE TITLE
Installation error on Amazon Linux (Cloud9)

### ISSUE THREAD

**Issue by cgswong** [serverless/components#298]
# Description
During installation, `npm install --global serverless-components`, I get the below error:

```
/home/ec2-user/.nvm/versions/node/v6.14.4/bin/components -> /home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/serverless-components/bin/components

> serverless-components@0.2.0 postinstall /home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/serverless-components
> node ./scripts/postinstall.js

/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/serverless-components/src/utils/index.js:15
  ...components,
  ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/serverless-components/scripts/postinstall.js:7:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless-components@0.2.0 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless-components@0.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-10-02T13_46_28_441Z-debug.log
```

## Additional Data

node: v6.14.4
npm: 6.4.1
OS: Amazon Linux 2018.03

Log snippet:

```
7184 info lifecycle serverless-components@0.2.0~postinstall: serverless-components@0.2.0
7185 verbose lifecycle serverless-components@0.2.0~postinstall: unsafe-perm in lifecycle true
7186 verbose lifecycle serverless-components@0.2.0~postinstall: PATH: /home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/serverless-components/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/.bin:/home/ec2-user/environment/scripts:/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/gems/ruby-2.4.1@global/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/home/ec2-user/.nvm/versions/node/v6.14.4/bin:/usr/local/bin:/bin:/usr/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/opt/aws/bin:/usr/local/rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin
7187 verbose lifecycle serverless-components@0.2.0~postinstall: CWD: /home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/serverless-components
7188 silly lifecycle serverless-components@0.2.0~postinstall: Args: [ '-c', 'node ./scripts/postinstall.js' ]
7189 silly lifecycle serverless-components@0.2.0~postinstall: Returned: code: 1  signal: null
7190 info lifecycle serverless-components@0.2.0~postinstall: Failed to exec postinstall script
7191 timing action:postinstall Completed in 124ms
7192 verbose unlock done using /home/ec2-user/.npm/_locks/staging-2a9152a3641ab43f.lock for /home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/.staging
7193 timing stage:rollbackFailedOptional Completed in 1371ms
7194 timing stage:runTopLevelLifecycles Completed in 13139ms
7195 verbose stack Error: serverless-components@0.2.0 postinstall: `node ./scripts/postinstall.js`
7195 verbose stack Exit status 1
7195 verbose stack     at EventEmitter.<anonymous> (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
7195 verbose stack     at emitTwo (events.js:106:13)
7195 verbose stack     at EventEmitter.emit (events.js:191:7)
7195 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v6.14.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
7195 verbose stack     at emitTwo (events.js:106:13)
7195 verbose stack     at ChildProcess.emit (events.js:191:7)
7195 verbose stack     at maybeClose (internal/child_process.js:920:16)
7195 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
7196 verbose pkgid serverless-components@0.2.0
7197 verbose cwd /home/ec2-user/environment
7198 verbose Linux 4.14.70-67.55.amzn1.x86_64
7199 verbose argv "/home/ec2-user/.nvm/versions/node/v6.14.4/bin/node" "/home/ec2-user/.nvm/versions/node/v6.14.4/bin/npm" "install" "--global" "serverless-components"
7200 verbose node v6.14.4
7201 verbose npm  v6.4.1
7202 error code ELIFECYCLE
7203 error errno 1
7204 error serverless-components@0.2.0 postinstall: `node ./scripts/postinstall.js`
7204 error Exit status 1
7205 error Failed at the serverless-components@0.2.0 postinstall script.
7205 error This is probably not a problem with npm. There is likely additional logging output above.
7206 verbose exit [ 1, true ]
```

**Comment by cgswong** [comment]
I realized I was not using the correct node version, however, when I switched to v8.12.0 I get the following error:

```
/home/ec2-user/.nvm/versions/node/v8.12.0/bin/components -> /home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components/bin/components

> serverless-components@0.2.0 postinstall /home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components
> node ./scripts/postinstall.js

(node:6196) UnhandledPromiseRejectionWarning: Error: Query timed out
    at DNS._ontimeout (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components/node_modules/dns-socket/index.js:99:18)
    at Timeout.ontimeout (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components/node_modules/dns-socket/index.js:53:10)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:6196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @serverless-components/eventgateway@0.2.0
added 13 packages from 11 contributors in 50.19s

+ @serverless-components/rest-api@0.2.0
added 2 packages from 4 contributors in 50.123s

+ @serverless-components/aws-iam-policy@0.2.0
added 16 packages from 67 contributors in 51.537s

+ @serverless-components/aws-lambda@0.2.0
added 57 packages from 88 contributors in 52.539s

+ @serverless-components/s3-dirloader@0.2.0
added 45 packages from 135 contributors in 53.539s

+ @serverless-components/aws-iam-role@0.2.0
added 17 packages from 71 contributors in 54.919s


> dtrace-provider@0.6.0 install /home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components/registry/aws-dynamodb/node_modules/dtrace-provider
> node scripts/install.js


+ @serverless-components/aws-dynamodb@0.2.0
added 48 packages from 110 contributors in 56.619s

+ github-webhook@0.2.0
added 43 packages from 36 contributors in 56.918s

+ @serverless-components/aws-s3-bucket@0.2.0
added 15 packages from 66 contributors in 57.785s

+ @serverless-components/s3-uploader@0.2.0
added 14 packages from 12 contributors in 57.795s

+ @serverless-components/aws-apigateway@0.2.0
added 16 packages from 70 contributors in 59.595s

+ @serverless-components/aws-cloudfront@0.2.0
added 15 packages from 66 contributors in 60.098s

+ @serverless-components/s3-downloader@0.2.0
added 2 packages from 5 contributors in 59.6s

+ @serverless-components/github-webhook-aws@0.2.0
added 1 package in 60.011s

+ netlify-site@0.2.0
added 4 packages from 13 contributors in 60.228s

+ @serverless-components/mustache@0.2.0
added 13 packages from 9 contributors in 60.48s

+ @serverless-components/static-website@0.2.0
added 2 packages from 4 contributors in 60.369s

+ @serverless-components/aws-route53@0.2.0
added 15 packages from 66 contributors in 61.614s

+ serverless-components@0.2.0
added 255 packages from 257 contributors in 76.777s
```

**Comment by brianneisler** [comment]
@cgswong, thanks for reporting this issue. We've recently added support for node 6 using babel compilation. Hopefully you won't have problems with node 6 anymore after we release a new version. 

In regards to your second error, this looks like a dns timeout. Were you able to replicate this issue consistently? We could probably add some retry logic here or extend the timeout to address the issue.

**Comment by cgswong** [comment]
Please ignore the first error as that was using a non-supported npm version. My 2nd posting is the one to be used as it is using a supported npm version. But to answer your question, yes. I can repeat the DNS timeout consistently:

```
admin-aws-role:~/environment $ node --version
v8.12.0
admin-aws-role:~/environment $ npm install --global serverless-components
/home/ec2-user/.nvm/versions/node/v8.12.0/bin/components -> /home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components/bin/components

> serverless-components@0.2.0 postinstall /home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components
> node ./scripts/postinstall.js

(node:4357) UnhandledPromiseRejectionWarning: Error: Query timed out
    at DNS._ontimeout (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components/node_modules/dns-socket/index.js:99:18)
    at Timeout.ontimeout (/home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components/node_modules/dns-socket/index.js:53:10)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:4357) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4357) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

+ @serverless-components/github-webhook-aws@0.2.0
updated 1 package in 50.238s

+ netlify-site@0.2.0
added 3 packages from 13 contributors and updated 1 package in 50.38s

+ @serverless-components/mustache@0.2.0
added 12 packages from 9 contributors and updated 1 package in 50.605s

+ @serverless-components/aws-route53@0.2.0
added 14 packages from 66 contributors and updated 1 package in 51.509s

+ @serverless-components/s3-uploader@0.2.0
added 13 packages from 12 contributors and updated 1 package in 51.338s

+ @serverless-components/eventgateway@0.2.0
added 12 packages from 11 contributors and updated 1 package in 51.982s

+ @serverless-components/static-website@0.2.0
added 1 package from 4 contributors and updated 1 package in 51.804s

+ @serverless-components/s3-dirloader@0.2.0
added 44 packages from 135 contributors and updated 1 package in 53.326s

+ github-webhook@0.2.0
added 42 packages from 36 contributors and updated 1 package in 54.285s

+ @serverless-components/aws-cloudfront@0.2.0
added 14 packages from 66 contributors and updated 1 package in 55.304s

+ @serverless-components/aws-s3-bucket@0.2.0
added 14 packages from 66 contributors and updated 1 package in 55.869s

+ @serverless-components/aws-apigateway@0.2.0
added 15 packages from 70 contributors and updated 1 package in 57.004s

+ @serverless-components/rest-api@0.2.0
added 1 package from 4 contributors and updated 1 package in 56.636s

+ @serverless-components/aws-iam-role@0.2.0
added 16 packages from 71 contributors and updated 1 package in 58.057s

+ @serverless-components/aws-iam-policy@0.2.0
added 15 packages from 67 contributors and updated 1 package in 58.849s

+ @serverless-components/aws-lambda@0.2.0
added 56 packages from 88 contributors and updated 1 package in 60.02s


> dtrace-provider@0.6.0 install /home/ec2-user/.nvm/versions/node/v8.12.0/lib/node_modules/serverless-components/registry/aws-dynamodb/node_modules/dtrace-provider
> node scripts/install.js


+ @serverless-components/aws-dynamodb@0.2.0
added 47 packages from 110 contributors and updated 1 package in 61.504s

+ @serverless-components/s3-downloader@0.2.0
added 1 package from 5 contributors and updated 1 package in 61.144s

+ serverless-components@0.2.0
removed 7 packages and updated 14 packages in 77.226s
```

I did some researching and the DNS timeout may be due to timeout in the library used so extending may address that issue.

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
