### ISSUE TITLE
input.hostingDomain error

### ISSUE THREAD

**Issue by moritz31** [serverless/components#299]
# Description

Try to run the serverless-components example and get this error.
The hostingDomain is not mandatory based on documentation. 
Is there an error somewhere or is the doku out of date?

## Additional Data

`Error: Referenced input does not exist for variable input.hostingDomain
    at resolveReferenceToValue (/home/moritz/.node_modules/lib/node_modules/serverless-components/src/utils/variables/resolvePreExecutionVars.js:42:19)
    at resolveValue (/home/moritz/.node_modules/lib/node_modules/serverless-components/src/utils/variables/resolvePreExecutionVars.js:55:16)
    at XWrap.f (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:60:20)
    at XWrap.@@transducer/step (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_xwrap.js:12:17)
    at _arrayReduce (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:11:34)
    at _reduce (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:45:12)
    at map (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:59:14)
    at /home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at f2 (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_curry2.js:29:14)
    at resolveValue (/home/moritz/.node_modules/lib/node_modules/serverless-components/src/utils/variables/resolvePreExecutionVars.js:10:14)
    at XWrap.f (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:60:20)
    at XWrap.@@transducer/step (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_xwrap.js:12:17)
    at _arrayReduce (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:11:34)
    at _reduce (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:45:12)
    at map (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:59:14)
    at /home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at f2 (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_curry2.js:29:14)
    at resolveValue (/home/moritz/.node_modules/lib/node_modules/serverless-components/src/utils/variables/resolvePreExecutionVars.js:10:14)
    at XWrap.f (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:60:20)
    at XWrap.@@transducer/step (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_xwrap.js:12:17)
    at _arrayReduce (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:11:34)
    at _reduce (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:45:12)
    at map (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:59:14)
    at /home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at f2 (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_curry2.js:29:14)
    at resolveValue (/home/moritz/.node_modules/lib/node_modules/serverless-components/src/utils/variables/resolvePreExecutionVars.js:10:14)
    at XWrap.f (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:60:20)
    at XWrap.@@transducer/step (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_xwrap.js:12:17)
    at _arrayReduce (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:11:34)
    at _reduce (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:45:12)
    at map (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:59:14)
    at /home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at f2 (/home/moritz/.node_modules/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_curry2.js:29:14)
    at module.exports (/home/moritz/.node_modules/lib/node_modules/serverless-components/src/utils/variables/resolvePreExecutionVars.js:68:10)
    at module.exports (/home/moritz/.node_modules/lib/node_modules/serverless-components/src/utils/components/getComponent.js:30:18)`

E.g. stack trace, version, operating system, ...

**Comment by brianneisler** [comment]
Thanks for reporting this issue @moritz31. We're overhauling the static-website component this sprint so this issue should get fixed. Can you let me know which example you were trying to run and we'll make sure the example gets updated as well.

**Comment by moritz31** [comment]
@brianneisler i tried the retail-app :) If you need anyhelp drop me an message 👍

**Comment by ptrhck** [comment]
I am also having the same issue. Any update on this?

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
