### ISSUE TITLE
Running components in a directory with serverless.yml for sls causes crash

### ISSUE THREAD

**Issue by pablojudd** [serverless/components#302]
# Description
Running components in a directory with serverless.yml designed for sls causes it to crash. Components should probably exit with a message showing the missing options in serverless.yml

## Additional Data
```
TypeError: Cannot read property 'self:service' of undefined
    at value.replace (/usr/local/lib/node_modules/serverless-components/src/utils/variables/transformPostExecutionVars.js:18:34)
    at String.replace (<anonymous>)
    at transformValue (/usr/local/lib/node_modules/serverless-components/src/utils/variables/transformPostExecutionVars.js:14:20)
    at XWrap.f (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:60:20)
    at XWrap.@@transducer/step (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_xwrap.js:12:17)
    at _arrayReduce (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:11:34)
    at _reduce (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:45:12)
    at map (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:59:14)
    at /usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at f2 (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_curry2.js:29:14)
    at transformValue (/usr/local/lib/node_modules/serverless-components/src/utils/variables/transformPostExecutionVars.js:11:14)
    at XWrap.f (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:60:20)
    at XWrap.@@transducer/step (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_xwrap.js:12:17)
    at _arrayReduce (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:11:34)
    at _reduce (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:45:12)
    at map (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:59:14)
    at /usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at f2 (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_curry2.js:29:14)
    at transformValue (/usr/local/lib/node_modules/serverless-components/src/utils/variables/transformPostExecutionVars.js:11:14)
    at XWrap.f (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:60:20)
    at XWrap.@@transducer/step (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_xwrap.js:12:17)
    at _arrayReduce (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:11:34)
    at _reduce (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_reduce.js:45:12)
    at map (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/map.js:59:14)
    at /usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_dispatchable.js:41:15
    at f2 (/usr/local/lib/node_modules/serverless-components/node_modules/ramda/src/internal/_curry2.js:29:14)
    at module.exports (/usr/local/lib/node_modules/serverless-components/src/utils/variables/transformPostExecutionVars.js:33:10)
    at module.exports (/usr/local/lib/node_modules/serverless-components/src/utils/components/getComponent.js:21:18)
    at <anonymous>
```

**Comment by brianneisler** [comment]
Thanks for reporting this issue @pablojudd. Seems like a pretty simple fix. Would be good to simply detect a serverless.yml made for sls and then output that components is not currently backward compatible with a serverless v1 project.

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
