### ISSUE TITLE
Unable to create resource at path

### ISSUE THREAD

**Issue by 82949712** [serverless/components#319]
# Description
Hi I'm trying to deploy the sample restapi components but I'm getting the following error

(node:150324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ BadRequestException: Errors found during import:
        Unable to create resource at path '/\faker': Resource's path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end.
    at Object.extractError (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.extractError (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\protocol\rest_json.js:52:8)
    at Request.callListeners (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\request.js:685:12)
    at Request.callListeners (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at callNextListener (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\sequential_executor.js:96:12)
    at IncomingMessage.onEnd (C:\Users\chong.l\AppData\Roaming\npm\node_modules\serverless-components\registry\aws-apigateway\node_modules\aws-sdk\lib\event_listeners.js:294:13)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'Errors found during import:\n\tUnable to create resource at path \'/\\faker\': Resource\'s path part only allow a-zA-Z0-9._- and curly braces at the beginning and the end.',
  code: 'BadRequestException',
  time: 2018-11-02T02:57:03.001Z,
  requestId: 'f9569ff6-de4a-11e8-8ed5-d7f5470eb64f',
  statusCode: 400,
  retryable: false,
  retryDelay: 45.48784499877616 }

## Additional Data
Here's the serverless.yml
type: faker-api
version: 0.0.1

components:
  createFakerData:
    type: aws-lambda
    inputs:
      memory: 512
      timeout: 10
      handler: faker.create
      root: ${self.path}/code
  fakerApi:
    type: rest-api
    inputs:
      gateway: aws-apigateway
      routes:
        /faker:
          post:
            function: ${createFakerData}
            cors: true

**Comment by PierreNedelec** [comment]
Hello same issue on Windows . it's working on Linux machine.

**Comment by Jltp1972** [comment]
Any solutions? Getting the same error on Windows.

**Comment by eahefnawy** [comment]
closing this as we've made a complete rewrite of the core and this issue is no longer applicable.
