### ISSUE TITLE
Bug irregularly causes failed deployments

### ISSUE THREAD

**Issue by ac360** [serverless/components#428]
I get this bug in 30% of my deployments.  It's been difficult to recreate, but it causes 30% of deployments to crash currently.

```
 my-chat-app › error:
  { NoSuchBucket: The specified bucket does not exist
    at Request.extractError (/Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/austen/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6/node_modules/aws-sdk/lib/request.js:685:12)
```

**Comment by eahefnawy** [comment]
@ac360 I tried all components that uses the bucket components with try/catch on all bucket operations, and was finally able to pin point the issue. It seems that enabling acceleration requires sleeping for couple of seconds after bucket creation. So I added that:

https://github.com/serverless-components/AwsS3/blob/master/serverless.js#L37-L41

After adding it, I tried it multiple times and wasn't able to reproduce it again. So this should fix it.

**Comment by eahefnawy** [comment]
You'll likely need to reset the cache to get this particular dependency update though.

```
rm -rf ~/.serverless/components/registry/npm
```

or at least the realtimeApp cache:

```
rm -rf ~/.serverless/components/registry/npm/@serverless/realtime-app@0.1.6
```

this highlights an issue we discussed earlier about updating cached components dependencies. We should probably introduce some `components --update` flag to force redownloading & installing latest dependencies from npm. Or maybe we could check the dependency tree on npm and do that automatically 🤔 

Opened an issue for that here:
https://github.com/serverless/components/issues/429
