### ISSUE TITLE
Backend with custom domain does not deploy in eu-west-2 region

### ISSUE THREAD

**Issue by eahefnawy** [serverless/components#470]
```yml
name: serverlesstest

app:
    component: '@serverless/website'
    inputs:
        region: eu-west-2
        domain: www.domain.tld
        memory: 256
        timeout: 10
        code:
            src: public/
            root: app
            
api:
    component: '@serverless/backend'
    inputs:
        region: eu-west-2
        domain: api.domain.tld
        memory: 256
        timeout: 10
        code:
            src: api

```

```
 ✘  patie@mbp-2  ~/web/my/serverlesstest  serverless
  error:
  Error: BadRequestException: Invalid REST API identifier specified
    at deployApiDomain (/Users/patie/.serverless/components/registry/npm/@serverless/backend@3.1.0/node_modules/@serverless/domain/utils.js:372:11)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  20s › app › Error: BadRequestException: Invalid REST API identifier specified
```

**Comment by eahefnawy** [comment]
Fixed
