### ISSUE TITLE
Serverless Components won't work with version 2.0.25.

### ISSUE THREAD

**Issue by Bastczuak** [serverless/components#529]
# Description
I'm trying to create my own component by following the official docu in this repo. By running `serverless` I always get the error below. I compared it with the official components and found out that they still use the old `1.0.0` version. Downgrading to `1.0.0` resolves the error.

## Additional Data
Used `serverless` version: `1.58.0`
Used `@serverless/core` version: `2.0.25`
Output after running serverless --debug
```bash
 error:
  TypeError: Cannot read property 'name' of undefined
    at new Component (/Users/srichter/software/website/node_modules/@serverless/core/Component.js:108:24)
    at new Website (/Users/srichter/software/website/serverless.js:2:1)
    at Object.runComponents (/Users/srichter/software/website/node_modules/@serverless/cli/src/index.js:195:23)
    at Object.<anonymous> (/Users/srichter/software/website/node_modules/serverless/bin/serverless.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```

## How to reproduce
Clone the official website component. Change version of @serverless/core to 2.0.25. Try run serverless --debug or --watch. Boom error.

**Comment by barrysteyn** [comment]
This exact same problem is happening to us as well. @Pavel910 can you confirm that when upgrading to 2.0.25, you get the same error?

**Comment by eahefnawy** [comment]
@barrysteyn @Bastczuak Please use v1 of the core. V2 is still experimental, hence the major pump.

**Comment by eahefnawy** [comment]
Sorry about this folks. I should've released it under an experimental tag and definitely not `latest`. I've fixed the latest tag to point to `1.1.2` as expected.

Thanks all for the nudge!

**Comment by Pavel910** [comment]
@barrysteyn looks like I'm late to the party :D I haven't noticed the problem as I'm not using the `serverless` CLI itself. I have the `@serverless/core` package as a dependency locked to `^1.x.x` so the wrong tag didn't have any influence on my project.

Glad @eahefnawy figured out what's wrong 👍

**Comment by barrysteyn** [comment]
Thanks everyone. @Bastczuak I think this issue can be closed now.
