### ISSUE TITLE
Request timed out after 60 seconds

### ISSUE THREAD

**Issue by Gabiras12** [serverless/components#959]
# Description
Hi. I'm developing a serverless component and we need to wait for CloudFront Status to change. I'm using the waitFor SDK function. The SDK part works. The problem is that it can take a long time and looks like serverless components have a timeout of 60s. Is this correct? How can I change it?

## Additional Data
```
Awaiting CF status to be deployed...
 Error: Request timed out after 60 seconds
    at poll (/builds/emerald-works/nova/manage-content/node_modules/@serverless/platform-client/src/instance.js:366:13)
    at poll (/builds/emerald-works/nova/manage-content/node_modules/@serverless/platform-client/src/instance.js:388:12)
    at async action (/builds/emerald-works/nova/manage-content/node_modules/@serverless/components/src/cli/commands/run.js:146:16)
    at async Object.module.exports [as run] (/builds/emerald-works/nova/manage-content/node_modules/@serverless/components/src/cli/commands/run.js:163:18)
    at async Object.module.exports (/builds/emerald-works/nova/manage-content/node_modules/@serverless/components/src/cli/index.js:196:7)
62s › Serverless › Request timed out after 60 seconds 
  Documentation: https://github.com/serverless/components 
  Support: https://app.serverless.com/support 
  Slack: https://www.serverless.com/slack/ 
```

**Comment by JoaquinFernandez** [comment]
Hi @Gabiras12 Did you eventually find a solution for this?

I am having the same problem, and there seem to be no documentation on this
